name: Self test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: testbuild
      run: |
        cd testdata
        g++ --version
        g++ ./test.cpp -o test
        ls
        ./test
    - uses: srz-zumix/reviewdog-cpplint@master
      with:
        github_token: ${{ secrets.github_token }}
        reporter: local
        flags: --linelength=50
        reviewdog_diff: 'git diff HEAD^'
        debug: true
