name: Self test
on: [push]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: srz-zumix/reviewdog-cpplint@master
      with:
        github_token: ${{ secrets.github_token }}
        reporter: local
        flags: --linelength=10
        reviewdog_options: '-diff=""git diff HEAD^""'
        debug: true
